# Generated by Django 5.2.7 on 2026-02-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepartoPropina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reparto', models.DateTimeField(auto_now_add=True)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EN', 'Enviado'), ('PA', 'Pagado'), ('RE', 'Rechazado')], default='PE', max_length=2)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.comercio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.comercio')),
            ],
            options={
                'unique_together': {('id_comercio', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Propina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('AP', 'Aprobado'), ('PE', 'Pendiente'), ('RE', 'Rechazado'), ('DE', 'Devuelto')], default='PE', max_length=2)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.comercio')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'comercio'], name='payments_pr_fecha_010412_idx')],
            },
        ),
    ]
