# Generated by Django 5.2.7 on 2026-02-11 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TieneAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.comercio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'comercio', 'fecha_ingreso')},
            },
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('cantidad_horas', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.tieneasignado')),
            ],
        ),
    ]
