# Generated by Django 5.2.7 on 2026-02-11 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(max_length=100)),
                ('tipo_comercio', models.CharField(choices=[('restaurante', 'Restaurante'), ('bar', 'Bar'), ('cafe', 'Café'), ('otros', 'Otros')], default='restaurante', max_length=20)),
                ('nombre_calle', models.CharField(max_length=50)),
                ('numero_calle', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, upload_to='comercio_images/')),
                ('ccreada', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ciudad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comercios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='codigo_qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='codigo_qr')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.comercio')),
            ],
        ),
    ]
