# Generated by Django 5.0.4 on 2024-07-26 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adherircom', '0015_rename_ingresos_empleado_ingresos_diarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.comercio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkinouts', to='Adherircom.empleado')),
            ],
        ),
    ]
