# Generated by Django 5.0.4 on 2024-07-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiProppi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='hora_entrada',
            field=models.DateTimeField(),
        ),
    ]
