# Generated by Django 5.0.4 on 2024-07-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuentamain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresosproppi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalusuarios', models.IntegerField(default=0)),
                ('totalcomercios', models.IntegerField(default=0)),
                ('totalempleados', models.IntegerField(default=0)),
            ],
        ),
    ]
