# Generated by Django 5.0.4 on 2024-07-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentamaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentamain',
            name='totingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
