# Generated by Django 5.2.1 on 2025-05-28 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(max_length=100)),
                ('tipo_comercio', models.CharField(choices=[('restaurante', 'Restaurante'), ('bar', 'Bar'), ('cafe', 'Café'), ('otros', 'Otros')], default='restaurante', max_length=20)),
                ('nombre_calle', models.CharField(max_length=50)),
                ('numero_calle', models.CharField(max_length=10)),
                ('imagen', models.ImageField(blank=True, upload_to='comercio_images/')),
                ('codigo_qr', models.ImageField(blank=True, upload_to='codigo_qr')),
                ('ccreada', models.DateTimeField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adherircom.ciudad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comercios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('cantidad_horas', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.comercio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adherircom.ciudad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.provincia'),
        ),
        migrations.CreateModel(
            name='RepartoPropina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reparto', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.comercio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.comercio')),
            ],
            options={
                'unique_together': {('id_comercio', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Propina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pagado', models.BooleanField(default=False)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.comercio')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'comercio'], name='Adherircom__fecha_ea0cbe_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('nombre', 'provincia')},
        ),
        migrations.CreateModel(
            name='TieneAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('id_comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.comercio')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.empleado')),
            ],
            options={
                'unique_together': {('id_empleado', 'id_comercio', 'fecha_ingreso')},
            },
        ),
    ]
