# Generated by Django 5.0.8 on 2024-10-15 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercio', models.CharField(max_length=100)),
                ('tipo_comercio', models.CharField(choices=[('restaurante', 'Restaurante'), ('bar', 'Bar'), ('cafe', 'Café'), ('otros', 'Otros')], default='restaurante', max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, upload_to='comercio_images/')),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('ingresos_diarios', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('ingresos_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('codigo_qr', models.ImageField(blank=True, upload_to='codigo_qr')),
                ('codigo_qr_entrada', models.ImageField(blank=True, upload_to='codigo_qr_entrada')),
                ('ccreada', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comercios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=35)),
                ('alias', models.CharField(max_length=40)),
                ('cuil', models.CharField(max_length=20, unique=True)),
                ('ingresos_diarios', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ingresos_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comercios', models.ManyToManyField(related_name='empleados', to='Adherircom.comercio')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('cantidad_horas', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_empleado', to='Adherircom.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(blank=True, max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pagado', models.BooleanField(default=False)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adherircom.comercio')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'comercio'], name='Adherircom__fecha_ea0cbe_idx')],
            },
        ),
    ]
