# Generated by Django 5.2.1 on 2025-07-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0002_alter_ciudad_nombre_alter_provincia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
