# Generated by Django 5.2.1 on 2025-07-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0003_alter_ciudad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='numero_calle',
            field=models.PositiveIntegerField(),
        ),
    ]
