# Generated by Django 5.0.4 on 2024-07-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0005_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariotrabajo',
            name='dias_semana',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')]),
        ),
        migrations.DeleteModel(
            name='DiaSemana',
        ),
    ]
