# Generated by Django 5.0.4 on 2024-07-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0006_alter_horariotrabajo_dias_semana_delete_diasemana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariotrabajo',
            name='dias_semana',
            field=models.JSONField(),
        ),
    ]
