# Generated by Django 5.0.4 on 2024-07-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0008_alter_comercio_user_alter_horariotrabajo_dias_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariotrabajo',
            name='dias_semana',
        ),
        migrations.AddField(
            model_name='horariotrabajo',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], default=1),
            preserve_default=False,
        ),
    ]
