# Generated by Django 5.0.4 on 2024-07-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0009_remove_horariotrabajo_dias_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='ingresos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='totingresos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
