# Generated by Django 5.0.4 on 2024-07-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0010_alter_comercio_ingresos_alter_comercio_totingresos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
