# Generated by Django 5.0.4 on 2024-07-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0011_alter_empleado_ingresos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comercio',
            old_name='ingresos',
            new_name='ingresos_diarios',
        ),
        migrations.RenameField(
            model_name='comercio',
            old_name='totingresos',
            new_name='ingresos_total',
        ),
    ]
