# Generated by Django 5.0.4 on 2024-07-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0012_rename_ingresos_comercio_ingresos_diarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariotrabajo',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horariotrabajo',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='comercio',
            name='codigo_qr_entrada',
            field=models.ImageField(blank=True, upload_to='codigo_qr_entrada'),
        ),
        migrations.AddField(
            model_name='horariotrabajo',
            name='cantidad_horas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
