# Generated by Django 5.0.4 on 2024-07-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0013_remove_horariotrabajo_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
