# Generated by Django 5.0.4 on 2024-07-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0014_comercio_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='ingresos',
            new_name='ingresos_diarios',
        ),
        migrations.AddField(
            model_name='empleado',
            name='ingresos_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
