# Generated by Django 5.0.4 on 2024-07-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0015_rename_ingresos_empleado_ingresos_diarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariotrabajo',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
    ]
