# Generated by Django 5.0.4 on 2024-07-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0016_alter_horariotrabajo_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propina',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='propina',
            index=models.Index(fields=['fecha', 'comercio'], name='Adherircom__fecha_ea0cbe_idx'),
        ),
    ]
