# Generated by Django 5.0.4 on 2024-08-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0017_alter_propina_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='slug',
        ),
    ]
