# Generated by Django 5.0.4 on 2024-08-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0019_empleado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='comercios',
        ),
        migrations.AddField(
            model_name='empleado',
            name='comercios',
            field=models.ManyToManyField(related_name='empleados', to='Adherircom.comercio'),
        ),
    ]
