# Generated by Django 5.0.4 on 2024-08-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adherircom', '0020_remove_empleado_comercios_empleado_comercios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='clave_unica',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cuit',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
